### ISSUE TITLE
Broken link in COST blog post

### ISSUE THREAD

**Issue by michaelmior** [frankmcsherry/blog#16]
The link titled "better versions" which links to an improved algorithm for PageRank is broken. I believe the URL below refers to the same paper:

https://www.microsoft.com/en-us/research/publication/a-uniform-approach-to-accelerated-pagerank-computation/

**Comment by frankmcsherry** [comment]
Gah, silly MSFT changing all their links around. I'll see if I can't find a less-likely-to-randomly-change-each-time-MSFT-has-a-reorg link. :)

**Comment by frankmcsherry** [comment]
For the record, I am a jerk. The link that broke was to citeseer, not Microsoft. Also, the Microsoft version is available but the ACM version is behind a paywall, so if it wasn't for them I wouldn't be able to read my own work. I apologize, Microsoft!

**Comment by frankmcsherry** [comment]
I've just pushed a version with your new link; thank you very much! :D

**Comment by michaelmior** [comment]
Thanks for the quick fix :)
