### ISSUE TITLE
Comment on Differential Privacy article

### ISSUE THREAD

**Issue by practicalantagonist** [frankmcsherry/blog#8]
Here is extract from a article I am writing. This is the part about you:

Frank McSherry (one of the authors of 2006 paper) is great personification of a “clueless” obnoxious CS Theory researcher who thinks that he is smarter than everyone else.
In his recent blogpost he frequently uses following sentence, when pointed real issues with application of Differential Privacy. Here is the link https://github.com/frankmcsherry/blog/blob/master/posts/2016-02-03.md

""" Anyhow, differential privacy working as intended. Clueless people don’t get clear access to sensitive data about small populations, no matter how sure they are that it is safe."""

This particular statement repeated several times, in context of an “Intern” (a doctor) performing a count query on medical records with an expected results ~100. According to McSherry who has zero training in medicine and no knowledge about existing healthcare data dissemination practices, such a query is concerning.

It is Frank himself who is deluded about his knowledge and superiority.

A typical intern at any hospital has access to records of Hundreds of thousands of patients. And this access is not some statistical query system but access to entire reports/discharge notes etc.
Lets forget access to records for moment, a typical intern can also prescribe extremely lethal drugs that will instantly kill a patient. All these activities are monitored by auditing or post incidence a review system. The additional harm by giving access to a query system is minimal if not close to zero. However according to Frank everyone else is a clueless idiot and we must cede all decision making to Differential Privacy Researchers.

Frank is also completely ignorant of IMS Health vs Sorrell, Supreme court decision (6–3) which allowed Pharmaceutical Companies to use de-identified patient data to market to doctors. (another doomsday scenario that he presented without realizing the current reality. ) Hospitals and Insurers have unrestricted access to their own data for simple purpose of doing  “Quality Improvement” which involve thousands of individual problems, majority of them which cannot be refactored in to a differentially private query system.

At this point one has to ask, who do we rely on making sensible decisions regarding data privacy in medicine. Physicians, Public Health researchers who have long experience with medicine and ethical/moral challenges. Or libertarian zealots like Frank McShrerry who thinks everyone else is clueless idiot, and patients ought to sign 1000 consent for everyday, delivered via push notifications? What about dead patients, should wait for end of the times when undead roam the earth or Mr. McSherrys space aliens to revive them. 
Lets not have obnoxious researchers like Frank ruin the future of data privacy  by preaching extreme political ideology disguised as scientific approach. Lives of thousands of patients (your daughter, father, son, nephew) are at stake, lets not kill them by relying on Differential Privacy researchers who love to label everyone else as clueless. While having zero knowledge about the world as it exists today.

**Comment by frankmcsherry** [comment]
It looks like a very promising article. Thank you for the heads up!

**Comment by practicalantagonist** [comment]
I have decided against writing this,since there is nothing to be gained from stooping to the level of discourse in your post.
